version: "3.5"

networks:
  proxy:
    name: ${TRAEFIK_NETWORK_NAME}
    external: true
  internal:

volumes:
  nextcloud:
  mysqldir:

services:
  nextcloud:
    image: nextcloud:20
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud.config.php:/usr/src/nextcloud/config/custom.config.php
    labels:
      # Enable access.
      - "traefik.enable=true"

      # Route all requests to DOMAIN_NAME to this service.
      - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN_NAME}`)"

      # Enable Let's Encrypt.
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"

      # Enable port 80.
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

      # Add redirect middleware for carddav/caldav.
      - "traefik.http.middlewares.nextcloudreplace.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloudreplace.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nextcloudreplace.redirectregex.permanent=true"

      # Enable secure headers and redirect.
      - "traefik.http.routers.nextcloud.middlewares=secureheader,nextcloudreplace"

    networks:
      - proxy
      - internal
    depends_on:
      - db
      - smtp
      - redis
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: root
      MYSQL_HOST: db:3306
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      NEXTCLOUD_SYSTEM_EMAIL:
      NEXTCLOUD_PROXY_IP:
      NEXTCLOUD_DOMAIN_NAME: ${DOMAIN_NAME}
      REDIS_HOST: redis
      NEXTCLOUD_S3_BUCKET:
      NEXTCLOUD_S3_KEY:
      NEXTCLOUD_S3_SECRET:
      NEXTCLOUD_S3_HOSTNAME:
      NEXTCLOUD_S3_REGION:

  db:
    image: mariadb:10.4.10
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "nextcloud"
      MYSQL_ROOT_HOST: "%"
    restart: always
    volumes:
      - mysqldir:/var/lib/mysql
    networks:
      - internal
    labels:
      - traefik.enable=false

  smtp:
    image: namshi/smtp
    restart: always
    networks:
      - internal
    labels:
      - traefik.enable=false

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal

  cron:
    image: nextcloud:20-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - internal
